FROM nginx:alpine

COPY ./dist /usr/share/nginx/html
COPY ./docker/nginx.conf.template /etc/nginx/nginx.conf.template
COPY ./docker/entrypoint_alphashop_nginx.sh /entrypoint_alphashop_nginx.sh

EXPOSE 80

# # Definisce il comando principale che deve essere eseguito quando il container viene avviato
ENTRYPOINT [ "sh", "entrypoint_alphashop_nginx.sh" ]
