FROM nginx:alpine

COPY ./docker/nginx.conf.template /etc/nginx/nginx.conf.template
COPY ./docker/entrypoint_alphashop_nginx.sh /entrypoint.sh

# Make the script executable
RUN chmod +x /entrypoint.sh

# Copy the Angular build files
COPY ./dist /usr/share/nginx/html

EXPOSE 80

# Defines the main command that should be executed when the container is started
ENTRYPOINT [ "sh", "entrypoint.sh" ]
