FROM ubuntu:18.04

LABEL description="Custom MongoDB Docker image for AlphaShop" 

RUN apt-get update && apt-get install -y mongodb

# Create the MongoDB data directory
RUN mkdir -p var/lib/mongodb/data/

# Expose default port 27017 from the container to the host
EXPOSE 27017

#Start MongoDb
CMD ["mongod", "-f", "/etc/mongodb.conf"]



